### PR TITLE
feat: support django22, py38

### PR DESCRIPTION
**Pull request by joshuarli**
Want to support py36, py38, django 1.11 to 2.2 all at once if it isn't too hard. I think it'll just be addressing deprecation warnings really.

### CODE REVIEW

**Comment by mattrobenolt** [comment]
If you wanna upstream this, happy to pull it and upload new release, etc.

**Comment by joshuarli** [comment]
> If you wanna upstream this, happy to pull it and upload new release, etc.

Thanks matt, hopefully my changes meet your bar of excellence by the time they're ready.

**Comment by joshuarli** [comment]
We break specifically in SudoForm's `django.contrib.auth.authenticate` with django @ 5e31be1b96 `Refs #25187 -- Required the authenticate() method of authentication backends to have request as the first positional argument.`, if you look at Django's code the TypeError's swallowed and we don't get a chance at authentication.

**Comment by joshuarli** [comment]
```
> /Users/josh/dev/django/django/contrib/auth/__init__.py(72)authenticate()
(Pdb) inspect.getcallargs(backend.authenticate, request, **credentials)
*** TypeError: authenticate() got multiple values for argument 'username'
```

**Comment by joshuarli** [comment]
GHA doing great this morning.

**Comment by joshuarli** [comment]
We did it.

**Comment by joshuarli** [comment]
I'm going to try and get everything passing on Django 2.0 first: https://github.com/getsentry/sentry/pull/25894/
Then try manual django-sudo testing on staging. Passing that, I'll merge this, pin the sha.zip in sentry, and submit changes for upstream consideration.

**Comment by joshuarli** [comment]
Local testing with sentry + Django 1.11, it works.

**Review by billyvg — APPROVED** [review]
LGTM

**Pull request merged**
